### ISSUE TITLE
Not working with more than 1 test

### ISSUE THREAD

**Issue by Shinkei** [superwf/jest-with-puppeteer-core#1]
Hi @superwf I have been testing you approach but I realized that if you have more than 1 test file, you get an error
``` FAIL  __tests__/perro.test.js
  ● Test suite failed to run

    Cannot find module 'puppeteer'
    Require stack:
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-environment-puppeteer/index.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-runner/build/run_test.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-runner/build/test_worker.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-worker/build/child.js

      at Object.<anonymous> (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:8:41)

 FAIL  __tests__/google.test.js
  ● Test suite failed to run

    Cannot find module 'puppeteer'
    Require stack:
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-environment-puppeteer/index.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-runner/build/run_test.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-runner/build/test_worker.js
    - /Users/jorge/Programming/jest-with-puppeteer-core/node_modules/jest-worker/build/child.js

      at Object.<anonymous> (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:8:41)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.231s
```
**Do you know what could be the reason for this?**

**Comment by superwf** [comment]
move moduleAlias to jest-puppeteer config and fix it.

**Comment by superwf** [comment]
I update this repo, fetch and retry it.

**Comment by Shinkei** [comment]
Thanks :)
